[project]
name = "parent_child_chunk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "dify_plugin>=0.10.2",
    "pydantic>=2.13.5",
    "tiktoken>=0.14.0",
    "transformers>=5.16.1",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
