[project]
name = "lark_trigger"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# uv lock
dependencies = [
    "lark-oapi>=1.7.3",
    "cachetools>=7.1.8",
    "dify_plugin>=0.10.2",
    "werkzeug>=3.1.8",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
