[project]
name = "google-sra72z"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# Refresh the lockfile with: uv lock
dependencies = [
    "dify-plugin>=0.10.2",
    "pydantic>=2.13.5",
    "loguru>=0.7.3",
    "requests>=2.34.2",
    "setuptools>=84.0.0",
    "sniffio>=1.3.1",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = [
    "black>=26.5.1",
    "ruff>=0.16.6",
]
