[project]
name = "gemini-video"
version = "0.0.9"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "william.chen", email = "william.chen@originlinks.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dify_plugin>=0.10.2",
    "google-genai>=2.22.0",
    "httpx>=0.28.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
