[project]
name = "bitbucket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

# Refresh the lockfile after dependency changes with: uv lock
dependencies = [
    "atlassian-python-api>=5.0.4",
    "dify_plugin>=0.10.2",
    "pydub>=0.25.1",
    "setuptools>=84.0.0",
]

# uv run black . -C -l 100 && uv run ruff check --fix
[dependency-groups]
dev = []
